### ISSUE TITLE
Specified Visual already a child of another Visual or the root of a CompositionTarget

### ISSUE THREAD

**Issue by FranklinDM** [FranklinDM/HornSide#9]
This error keeps on coming up at the startup of HornSide. Will be fixed later.

System.ArgumentException: Specified Visual is already a child of another Visual or the root of a CompositionTarget.
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at LongBar.LongBarMain.LoadTilesAtStartup() in c:\Users\Francis Dominic\Documents\SharpDevelop Projects\Git\LongBarSlate\LongBar\LongBar.xaml.cs:line 281
   at LongBar.LongBarMain.DummyAnimation_Completed(Object sender, EventArgs e) in c:\Users\Francis Dominic\Documents\SharpDevelop Projects\Git\LongBarSlate\LongBar\LongBar.xaml.cs:line 226
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

**Comment by FranklinDM** [comment]
A _temporary bugfix_ for this issue has been committed, adding an empty general catch clause to suppress the error. It doesn't seem to have a negative effect over the behavior anyway.
